Sprint 2
timdancan/middle.messenger.praktikum.yandex pull request #4
Opened 2021-12-11 09:28 UTC by timdancan

2021-12-11 14:13 UTC, DmitryKhitrin requested changes
Привет, спасибо за отличную работу. Все выглядит отлично, кроме некоторых проблем с типизацией. TS призван помочь нам писать более надежный код, отлавливая ошибки еще на этапе написания кода. Расставляя везде any, мы часто просто сильно усложняем себе жизнь и ловим неожиданные ошибки в проде. Давай попробуем избавиться от any, хотя бы в базовом Block?

2021-12-11 14:13 UTC, khitrind commented on routes.ts
> +const changeUserPasswordPageRoute: Route = {
Лучше разбить энтрипоинты разных страниц на разные файлы, так код получится более читаемым

2021-12-11 14:13 UTC, khitrind commented on src/components/chats-list/chats-list.ts
> +    props.children = { ...(props.children ?? {}), ...ChatsList.getChatsListFromChats(props.chats) };
зачем тут везде спреды?

2021-12-11 14:13 UTC, khitrind commented on src/components/chats-list/chats-list.ts
> +  static getChatsListFromChats(chatItemPropsList: Chats): {
Это скорее просто `private` метод класса, зачем делать его static?

2021-12-11 14:13 UTC, DmitryKhitrin commented on src/helpers/classes/block.ts
> +  constructor(props: any, tagName = "div", classNames: string[] = []) {
Вот тут не стоит писать, any. Так код становится супер не надежным, ведь тут кто-нибудь может отнаследоваться от `Block` передать вместо props `undefined`. И программа упадет и узнаете вы об этом только в рантайме. Но выход есть - честные типы и [generics](https://www.typescriptlang.org/docs/handbook/2/generics.html).


В общем виде должно получиться, что-то такое:

```
abstract class Block<Props extends {}> {
    private element: HTMLElement;
    private tagName: string;

    protected props: Props;

    public constructor(tagName: string = 'div', propsAndChildren: Props) {
        this.tagName = tagName;
        this.props = propsAndChildren;
    }
}

type ButtonProps = {
    onClick: () => {};
};

class Button extends Block<ButtonProps> {
    public constructor(props: ButtonProps) {
        super('div', props);
    }

    public onClick() {
        this.props.onClick();
    }
}
```

2021-12-11 14:13 UTC, DmitryKhitrin commented on src/helpers/classes/event-bus.ts
> +  listeners: { [key: string]: ((...args: any[]) => void)[] };
Для типов вида `{[key: string]: string}` существует хэлпер [Record](https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeys-type):

`Record<string, string>`

2021-12-11 14:13 UTC, DmitryKhitrin commented on src/helpers/classes/request-service.ts
> +    .reduce((acc: string[], [key, value]) => {
Зачем тут массив, если сразу можно склеивать строку?

`reduce(() => {}, '?')`

2021-12-11 14:13 UTC, DmitryKhitrin commented on src/helpers/classes/request-service.ts
> +      if (options.method === API_METHOD.GET || !options.data) {
Зачем проверка на GET в общем методе, если тут хватит проверка просто на наличие data?

2021-12-11 14:13 UTC, DmitryKhitrin commented on src/helpers/classes/request-service.ts
> +      if (xhr.status !== 200 && retries && retries > 0) {
👍

2021-12-11 14:13 UTC, DmitryKhitrin commented on src/helpers/models/form-field.model.ts
> +  button = "button",
Ключи для enum, обычно называют с заглавной буквы

2021-12-11 14:13 UTC, DmitryKhitrin commented on src/helpers/models/route.model.ts
> +    pageClass: any;
Зачем тут any?

2021-12-12 10:15 UTC, timdancan commented on src/helpers/models/form-field.model.ts
> +  button = "button",
Буду знать, в дальнейшем буду писать правильно

2021-12-12 10:39 UTC, timdancan commented on routes.ts
> +const changeUserPasswordPageRoute: Route = {
Понял, попробую в следующем спринте раскидать по файлам

2021-12-12 15:21 UTC, DmitryKhitrin approved these changes

2021-12-12 15:21 UTC, DmitryKhitrin commented on src/helpers/classes/block.ts
> +  constructor(props: ObjectLiteral, tagName = "div", classNames: string[] = []) {
Луше все же дженерик, но так однозначно лучше, чем было раньше)

2021-12-22 13:47 UTC, merged